### ISSUE TITLE
Installing with npm

### ISSUE THREAD

**Issue by deltragon** [Sopamo/vue-online#3]
The description recommends installing vue-online using ``` npm install --save-dev vue-online ```
I believe this is incorrect, since devDependencies are not available/supposed to be available in runtime, making them useful for things like preprocessors/linters. However, vue-online is imported during runtime, and that's what regular dependencies are used for. This means the description should probably be changed to recommend installing using ``` npm install --save vue-online ```

**Comment by Sopamo** [comment]
I think the reasoning back then was that most projects have a build step where they include this library in the final build, thus not needing it anymore at runtime. But I guess it's more common to install these libraries in the regular dependencies so I'll change it. Thanks for the note!
